export const policiesEn = {
  title: "Guide Management",
  subtitle: "Manage UI/UX guides and generate professional reports.",
  filterAll: "All Domains",
  filterUnmatched: "Unmatched",
  searchPlaceholder: "Search by title, description, or selector...",
  noPolicies: "No guides yet.",
  noFilterResults: "No results match your search.",
  loadFailed: "Failed to load guides.",
  loading: "Loading guides...",
  retry: "Retry",
  coverageNone: "This pattern does not match any registered domain. Check the host pattern.",
  capturedOn: "Captured on",
  coverageIncluded: "Included",
  coverageExcluded: "Excluded",
  coverageSearchHosts: "Search domains...",
  coverageEmptyList: "No domains in this list.",
  filterHostPlaceholder: "Filter by host...",
  filterHostTypeToSearch: "Type to search...",
  filterHostClear: "Clear host filter",
  exportJson: "Export JSON",
  importJson: "Import JSON",
  exportPdf: "Generate PDF Report",
  policyCount: "guides",
  edit: "Edit",
  delete: "Delete",
  selector: "CSS Selector",
  tagName: "Tag",
  lastUpdated: "Last Updated",
  visitSite: "Visit Site",
  pdfFileName: "Guide_Report",
  deleteConfirm: "Are you sure you want to delete this guide?",
  importSuccess: "guides imported successfully.",
  exportSuccess: "Guide data saved as JSON.",
  zoom: "Zoom",
  save: "Save",
  cancel: "Cancel",
  roleLabel: "Element Title",
  descLabel: "Guide Details",
  displayOptions: "Report Fields",
  showSelector: "Selector",
  showTag: "Tag",
  showUrl: "URL",
  viewManage: "Manage Mode",
  viewPreview: "Report Preview",
  editPolicy: "Edit Guide Info",
  urlLabel: "Capture URL (origin)",
  domainLabel: "Capture host (origin)",
  hostPatternLabel: "Host Pattern",
  pathPatternLabel: "Path Pattern",
  hostPatternPlaceholder: "e.g. *.example.*, !api",
  pathPatternPlaceholder: "e.g. /products/*, /checkout (** = recursive)",
  patternHelp:
    "Matching uses Host Pattern only. * is a wildcard, ! excludes. Example: *.example.*, !api — domain/url is capture origin.",
  featureLinkInsert: "Insert feature link",
  featureLinkHint: "Type [[ to search feature links",
  featureLinkMocking: "Mocking",
  featureLinkLogs: "Logs",
  featureLinkSchema: "Schema",
  featureLinkLocal: "Local destination",
  featureLinkInject: "Injection",
  featureLinkNoDomain: "No registered domain matches this guide. Check the host pattern.",
  featureLinkUnavailable: "This panel is not available for the matched domain.",
  featureLinkUseHub: "Domain panels can only be opened from the hub window.",
  saveFailed: "Save failed.",
  saveRoleRequired: "Enter a role / title.",
  deleteFailed: "Delete failed.",
};
