export const policiesKo = {
  title: "가이드 관리",
  subtitle: "서비스별로 정의된 UI/UX 가이드를 관리하고 리포트를 생성합니다.",
  filterAll: "전체 도메인",
  filterUnmatched: "미매칭",
  searchPlaceholder: "가이드명, 설명, 선택자 검색...",
  noPolicies: "저장된 가이드가 없습니다.",
  noFilterResults: "검색 결과가 없습니다.",
  loadFailed: "가이드를 불러오지 못했습니다.",
  loading: "가이드를 불러오는 중...",
  retry: "다시 시도",
  coverageNone: "등록된 도메인과 맞지 않습니다. Host Pattern을 확인하세요.",
  capturedOn: "캡처",
  coverageIncluded: "들어가는 도메인",
  coverageExcluded: "안 들어가는 도메인",
  coverageSearchHosts: "도메인 검색...",
  coverageEmptyList: "해당하는 도메인이 없습니다.",
  filterHostPlaceholder: "호스트로 필터...",
  filterHostTypeToSearch: "검색어를 입력하세요",
  filterHostClear: "호스트 필터 해제",
  exportJson: "JSON 백업",
  importJson: "데이터 복원",
  exportPdf: "PDF 리포트 생성",
  policyCount: "개의 가이드",
  edit: "수정",
  delete: "삭제",
  selector: "CSS Selector",
  tagName: "Tag",
  lastUpdated: "최종 수정",
  visitSite: "사이트 방문",
  pdfFileName: "가이드_리포트",
  deleteConfirm: "정말 이 가이드를 삭제하시겠습니까?",
  importSuccess: "개의 가이드를 성공적으로 가져왔습니다.",
  exportSuccess: "가이드 데이터가 JSON 파일로 저장되었습니다.",
  zoom: "확대",
  save: "저장",
  cancel: "취소",
  roleLabel: "요소 명칭",
  descLabel: "가이드 내용",
  displayOptions: "리포트 노출 항목",
  showSelector: "Selector",
  showTag: "Tag",
  showUrl: "URL",
  viewManage: "관리 모드",
  viewPreview: "리포트 미리보기",
  editPolicy: "가이드 정보 수정",
  urlLabel: "캡처 URL (출처)",
  domainLabel: "캡처 호스트 (출처)",
  hostPatternLabel: "호스트 매칭 패턴 (Host Pattern)",
  pathPatternLabel: "경로 매칭 패턴 (Path Pattern)",
  hostPatternPlaceholder: "예: *.example.*, !api",
  pathPatternPlaceholder: "예: /products/*, /checkout (** = 전체 하위 경로)",
  patternHelp:
    "적용은 Host Pattern만 사용합니다. * 는 와일드카드, ! 는 제외입니다. 예: *.example.*, !api — domain/url은 캡처 출처입니다.",
  featureLinkInsert: "기능 링크 삽입",
  featureLinkHint: "[[ 검색으로 기능 링크 삽입",
  featureLinkMocking: "모킹",
  featureLinkLogs: "로그",
  featureLinkSchema: "스키마",
  featureLinkLocal: "로컬 목적지",
  featureLinkInject: "인젝션",
  featureLinkNoDomain: "이 가이드에 맞는 등록 도메인이 없습니다. 호스트 패턴을 확인하세요.",
  featureLinkUnavailable: "이 도메인에서 해당 패널을 열 수 없습니다.",
  featureLinkUseHub: "분리된 창에서는 허브의 도메인 패널을 열 수 없습니다.",
  saveFailed: "저장에 실패했습니다.",
  saveRoleRequired: "요소 명칭을 입력하세요.",
  deleteFailed: "삭제에 실패했습니다.",
};
