// This file has been generated by Tauri Specta. Do not edit this file manually.

import { invoke as __TAURI_INVOKE } from "@tauri-apps/api/core";

/** Commands */
export const commands = {
	getTransparentProxyStatus: () => typedError<ApiResponse<TransparentProxyStatus>, string>(__TAURI_INVOKE("get_transparent_proxy_status")),
	startTransparentProxy: (payload: {
	port: number | null,
	processNames?: string[] | null,
} | null) => typedError<ApiResponse<TransparentProxyStatus>, string>(__TAURI_INVOKE("start_transparent_proxy", { payload })),
	stopTransparentProxy: () => typedError<ApiResponse<TransparentProxyStatus>, string>(__TAURI_INVOKE("stop_transparent_proxy")),
	applyTransparentProxyApps: (payload: {
	processNames: string[],
	port: number | null,
}) => typedError<ApiResponse<TransparentProxyStatus>, string>(__TAURI_INVOKE("apply_transparent_proxy_apps", { payload })),
	scanOsApps: () => typedError<ApiResponse<OsAppEntry[]>, string>(__TAURI_INVOKE("scan_os_apps")),
	listTransparentProxyPresets: () => typedError<ApiResponse<string[]>, string>(__TAURI_INVOKE("list_transparent_proxy_presets")),
	registDomains: (payload: RegistDomainsPayload) => typedError<ApiResponse<Domain[]>, string>(__TAURI_INVOKE("regist_domains", { payload })),
	getDomains: () => typedError<ApiResponse<Domain[]>, string>(__TAURI_INVOKE("get_domains")),
	removeDomains: (payload: RemoveDomainsPayload) => typedError<ApiResponse<Domain | null>, string>(__TAURI_INVOKE("remove_domains", { payload })),
	getDomainById: (payload: GetDomainByIdPayload) => typedError<ApiResponse<Domain | null>, string>(__TAURI_INVOKE("get_domain_by_id", { payload })),
	updateDomainById: (payload: UpdateDomainByIdPayload) => typedError<ApiResponse<Domain | null>, string>(__TAURI_INVOKE("update_domain_by_id", { payload })),
	importDomains: (payload: ImportDomainsPayload) => typedError<ApiResponse<Domain[]>, string>(__TAURI_INVOKE("import_domains", { payload })),
	clearAllDomains: () => typedError<ApiResponse<Domain[]>, string>(__TAURI_INVOKE("clear_all_domains")),
	getLatestStatus: () => typedError<ApiResponse<DomainStatusLog[]>, string>(__TAURI_INVOKE("get_latest_status")),
	checkDomainStatus: () => typedError<ApiResponse<DomainStatusLog[]>, string>(__TAURI_INVOKE("check_domain_status")),
	getDomainStatusLogs: (payload: GetDomainStatusLogsPayload) => typedError<ApiResponse<DomainStatusLog[]>, string>(__TAURI_INVOKE("get_domain_status_logs", { payload })),
	getDomainGroupLinks: () => typedError<ApiResponse<DomainGroupLink[]>, string>(__TAURI_INVOKE("get_domain_group_links")),
	setDomainGroups: (payload: SetDomainGroupsPayload) => typedError<ApiResponse<null>, string>(__TAURI_INVOKE("set_domain_groups", { payload })),
	setGroupDomains: (payload: SetGroupDomainsPayload) => typedError<ApiResponse<null>, string>(__TAURI_INVOKE("set_group_domains", { payload })),
	getDomainsByGroup: (payload: GetDomainsByGroupPayload) => typedError<ApiResponse<Domain[]>, string>(__TAURI_INVOKE("get_domains_by_group", { payload })),
	getGroupsForDomain: (payload: GetGroupsForDomainPayload) => typedError<ApiResponse<DomainGroup[]>, string>(__TAURI_INVOKE("get_groups_for_domain", { payload })),
	createGroup: (payload: CreateGroupPayload) => typedError<ApiResponse<DomainGroup[]>, string>(__TAURI_INVOKE("create_group", { payload })),
	getGroups: () => typedError<ApiResponse<DomainGroup[]>, string>(__TAURI_INVOKE("get_groups")),
	deleteGroup: (payload: DeleteGroupPayload) => typedError<ApiResponse<DomainGroup[]>, string>(__TAURI_INVOKE("delete_group", { payload })),
	updateGroup: (payload: UpdateGroupPayload) => typedError<ApiResponse<DomainGroup[]>, string>(__TAURI_INVOKE("update_group", { payload })),
	getLocalRoutes: () => typedError<ApiResponse<LocalRoute[]>, string>(__TAURI_INVOKE("get_local_routes")),
	addLocalRoute: (payload: AddLocalRoutePayload) => typedError<ApiResponse<LocalRoute>, string>(__TAURI_INVOKE("add_local_route", { payload })),
	updateLocalRoute: (payload: UpdateLocalRoutePayload) => typedError<ApiResponse<LocalRoute | null>, string>(__TAURI_INVOKE("update_local_route", { payload })),
	removeLocalRoute: (payload: RemoveLocalRoutePayload) => typedError<ApiResponse<LocalRoute | null>, string>(__TAURI_INVOKE("remove_local_route", { payload })),
	setLocalRouteEnabled: (payload: SetLocalRouteEnabledPayload) => typedError<ApiResponse<LocalRoute | null>, string>(__TAURI_INVOKE("set_local_route_enabled", { payload })),
	getProxyStatus: () => typedError<ApiResponse<ProxyStatusPayload>, string>(__TAURI_INVOKE("get_proxy_status")),
	startLocalProxy: (payload: {
	port: number | null,
} | null) => typedError<ApiResponse<ProxyStatusPayload>, string>(__TAURI_INVOKE("start_local_proxy", { payload })),
	stopLocalProxy: () => typedError<ApiResponse<ProxyStatusPayload>, string>(__TAURI_INVOKE("stop_local_proxy")),
	getProxySettings: () => typedError<ApiResponse<ProxySettings>, string>(__TAURI_INVOKE("get_proxy_settings")),
	setProxyDnsServer: (payload: SetProxyDnsServerPayload) => typedError<ApiResponse<ProxySettings>, string>(__TAURI_INVOKE("set_proxy_dns_server", { payload })),
	setProxyPort: (payload: SetProxyPortPayload) => typedError<ApiResponse<ProxySettings>, string>(__TAURI_INVOKE("set_proxy_port", { payload })),
	setProxyReversePorts: (payload: SetProxyReversePortsPayload) => typedError<ApiResponse<ProxySettings>, string>(__TAURI_INVOKE("set_proxy_reverse_ports", { payload })),
	/**
	 *  Returns the setup page URL when proxy is running and a reverse port is configured.
	 *  Frontend can open this URL in the browser (e.g. via opener plugin).
	 */
	getProxySetupUrl: () => typedError<ApiResponse<string>, string>(__TAURI_INVOKE("get_proxy_setup_url")),
	exportAllSettings: () => typedError<ApiResponse<SettingsExport_Serialize>, string>(__TAURI_INVOKE("export_all_settings")),
	importAllSettings: (payload: SettingsExport_Deserialize, mode: string | null) => typedError<ApiResponse<boolean>, string>(__TAURI_INVOKE("import_all_settings", { payload, mode })),
	saveRootCa: () => typedError<ApiResponse<string>, string>(__TAURI_INVOKE("save_root_ca")),
	getDomainMonitorList: () => typedError<ApiResponse<DomainMonitorWithUrl[]>, string>(__TAURI_INVOKE("get_domain_monitor_list")),
	setDomainMonitorCheckEnabled: (payload: SetDomainMonitorCheckEnabledPayload) => typedError<ApiResponse<boolean>, string>(__TAURI_INVOKE("set_domain_monitor_check_enabled", { payload })),
	/**  모든 도메인 API 로깅 링크 조회. */
	getDomainApiLoggingLinks: () => typedError<ApiResponse<DomainApiLoggingLink_Serialize[]>, string>(__TAURI_INVOKE("get_domain_api_logging_links")),
	/**  도메인 API 로깅 설정 추가/변경. */
	setDomainApiLogging: (payload: SetDomainApiLoggingPayload) => typedError<ApiResponse<DomainApiLoggingLink_Serialize[]>, string>(__TAURI_INVOKE("set_domain_api_logging", { payload })),
	/**  도메인 API 로깅 설정 제거. */
	removeDomainApiLogging: (payload: RemoveDomainApiLoggingPayload) => typedError<ApiResponse<DomainApiLoggingLink_Serialize[]>, string>(__TAURI_INVOKE("remove_domain_api_logging", { payload })),
	/**  Schema URL에서 JSON/YAML을 다운로드하여 로컬 저장. */
	downloadApiSchema: (payload: DownloadApiSchemaPayload) => typedError<ApiResponse<SchemaDownloadResult>, string>(__TAURI_INVOKE("download_api_schema", { payload })),
	/**  로컬에 저장된 Schema 내용 조회. */
	getApiSchemaContent: (payload: GetApiSchemaPayload) => typedError<ApiResponse<string | null>, string>(__TAURI_INVOKE("get_api_schema_content", { payload })),
	/**
	 *  임의의 HTTP 요청을 전송하고 응답을 반환 (Schema Try-it-out).
	 *  네트워크 에러도 `ApiResponse로` 감싸서 반환 (Tauri invoke 예외 대신 FE에서 처리 가능).
	 */
	sendApiRequest: (payload: SendApiRequestPayload) => typedError<ApiResponse<ApiRequestResult>, string>(__TAURI_INVOKE("send_api_request", { payload })),
	updateProxySettings: (payload: UpdateProxySettingsPayload) => typedError<ApiResponse<ProxySettings>, string>(__TAURI_INVOKE("update_proxy_settings", { payload })),
	setHttpsDecryptHost: (payload: SetHttpsDecryptHostPayload) => typedError<ApiResponse<ProxySettings>, string>(__TAURI_INVOKE("set_https_decrypt_host", { payload })),
	/**  Returns the auto-start error if proxy failed to start on launch, or null if OK. */
	getProxyAutoStartError: () => typedError<ApiResponse<string | null>, string>(__TAURI_INVOKE("get_proxy_auto_start_error")),
	/**  API 로그 날짜 목록 조회. (YYYY-MM-DD) */
	listApiLogDates: () => typedError<ApiResponse<string[]>, string>(__TAURI_INVOKE("list_api_log_dates")),
	/**  특정 날짜의 API 로그 조회. */
	getApiLogs: (payload: GetApiLogsPayload) => typedError<ApiResponse<ApiLogEntry[]>, string>(__TAURI_INVOKE("get_api_logs", { payload })),
	getApiLogDetail: (payload: GetApiLogDetailPayload) => typedError<ApiResponse<ApiLogEntry | null>, string>(__TAURI_INVOKE("get_api_log_detail", { payload })),
	searchApiLogs: (payload: SearchApiLogsPayload) => typedError<ApiResponse<ApiLogSearchHit[]>, string>(__TAURI_INVOKE("search_api_logs", { payload })),
	/**  API 로그 삭제 (특정 날짜 또는 전체). */
	clearApiLogs: (payload: ClearApiLogsPayload) => typedError<ApiResponse<null>, string>(__TAURI_INVOKE("clear_api_logs", { payload })),
	openWindow: (label: string, title: string, url: string, width: number | null, height: number | null) => typedError<null, string>(__TAURI_INVOKE("open_window", { label, title, url, width, height })),
	openExternalUrl: (url: string) => typedError<null, string>(__TAURI_INVOKE("open_external_url", { url })),
	openInspectorWindow: (url: string, script: string | null) => typedError<null, string>(__TAURI_INVOKE("open_inspector_window", { url, script })),
	openAnnotationDialog: (selector: string, content: string, tagName: string, thumbnail: string) => typedError<null, string>(__TAURI_INVOKE("open_annotation_dialog", { selector, content, tagName, thumbnail })),
	quitApp: () => typedError<null, string>(__TAURI_INVOKE("quit_app")),
	prepareForUpdate: () => typedError<null, string>(__TAURI_INVOKE("prepare_for_update")),
	ensureServeRunning: () => typedError<null, string>(__TAURI_INVOKE("ensure_serve_running")),
	installWindowsUpdate: () => typedError<null, string>(__TAURI_INVOKE("install_windows_update")),
	captureAppScreenshot: () => typedError<string, string>(__TAURI_INVOKE("capture_app_screenshot")),
	triggerOsSnip: () => typedError<null, string>(__TAURI_INVOKE("trigger_os_snip")),
	chatEnsureIdentity: () => typedError<{ deviceId: string, publicKey: string }, string>(__TAURI_INVOKE("chat_ensure_identity")),
	chatDeriveDmKey: (myUserId: string, peerUserId: string, peerPublicKey: string) => typedError<string, string>(__TAURI_INVOKE("chat_derive_dm_key", { myUserId, peerUserId, peerPublicKey })),
	chatGenerateRoomKey: () => typedError<string, string>(__TAURI_INVOKE("chat_generate_room_key")),
	chatWrapRoomKey: (roomKey: string, peerPublicKey: string) => typedError<string, string>(__TAURI_INVOKE("chat_wrap_room_key", { roomKey, peerPublicKey })),
	chatUnwrapRoomKey: (wrapped: string) => typedError<string, string>(__TAURI_INVOKE("chat_unwrap_room_key", { wrapped })),
	chatSeal: (roomKey: string, plaintext: string) => typedError<string, string>(__TAURI_INVOKE("chat_seal", { roomKey, plaintext })),
	chatOpen: (roomKey: string, ciphertext: string) => typedError<string, string>(__TAURI_INVOKE("chat_open", { roomKey, ciphertext })),
	chatStartListener: () => typedError<{ port: number, lanHosts: string[] }, string>(__TAURI_INVOKE("chat_start_listener")),
	chatStopListener: () => typedError<null, string>(__TAURI_INVOKE("chat_stop_listener")),
	chatSendFrame: (lanHosts: string[], lanPort: number, tunnelUrl: string | null, frameJson: string) => typedError<{ state: string, via: string }, string>(__TAURI_INVOKE("chat_send_frame", { lanHosts, lanPort, tunnelUrl, frameJson })),
	playCommAction: (kind: string, seed: number | null, count: number | null, fromLabel: string | null) => typedError<null, string>(__TAURI_INVOKE("play_comm_action", { kind, seed, count, fromLabel })),
	setCommOverlayTool: (tool: string) => typedError<null, string>(__TAURI_INVOKE("set_comm_overlay_tool", { tool })),
	clearCommOverlay: () => typedError<null, string>(__TAURI_INVOKE("clear_comm_overlay")),
	getAnnotations: () => typedError<ApiResponse<Annotation_Serialize[]>, string>(__TAURI_INVOKE("get_annotations")),
	getAnnotation: (payload: GetAnnotationPayload) => typedError<ApiResponse<Annotation_Serialize | null>, string>(__TAURI_INVOKE("get_annotation", { payload })),
	addAnnotation: (payload: Annotation_Deserialize) => typedError<ApiResponse<Annotation_Serialize[]>, string>(__TAURI_INVOKE("add_annotation", { payload })),
	updateAnnotation: (payload: UpdateAnnotationPayload_Deserialize) => typedError<ApiResponse<Annotation_Serialize[]>, string>(__TAURI_INVOKE("update_annotation", { payload })),
	deleteAnnotation: (payload: DeleteAnnotationPayload) => typedError<ApiResponse<Annotation_Serialize[]>, string>(__TAURI_INVOKE("delete_annotation", { payload })),
	importAnnotations: (payload: ImportAnnotationsPayload_Deserialize) => typedError<ApiResponse<Annotation_Serialize[]>, string>(__TAURI_INVOKE("import_annotations", { payload })),
	getInjectionDomains: () => typedError<ApiResponse<string[]>, string>(__TAURI_INVOKE("get_injection_domains")),
	setInjectionDomains: (payload: SetInjectionDomainsPayload) => typedError<ApiResponse<string[]>, string>(__TAURI_INVOKE("set_injection_domains", { payload })),
	addInjectionDomain: (payload: SingleDomainPayload) => typedError<ApiResponse<string[]>, string>(__TAURI_INVOKE("add_injection_domain", { payload })),
	removeInjectionDomain: (payload: SingleDomainPayload) => typedError<ApiResponse<string[]>, string>(__TAURI_INVOKE("remove_injection_domain", { payload })),
	getScenarios: () => typedError<ApiResponse<Scenario[]>, string>(__TAURI_INVOKE("get_scenarios")),
	createScenario: (payload: CreateScenarioPayload) => typedError<ApiResponse<Scenario>, string>(__TAURI_INVOKE("create_scenario", { payload })),
	updateScenario: (id: string, name: string | null, description: string | null, enabled: boolean | null) => typedError<Scenario, string>(__TAURI_INVOKE("update_scenario", { id, name, description, enabled })),
	deleteScenario: (id: string) => typedError<boolean, string>(__TAURI_INVOKE("delete_scenario", { id })),
	getMockRules: () => typedError<ApiResponse<MockRule[]>, string>(__TAURI_INVOKE("get_mock_rules")),
	getMockRulesByScenario: (payload: GetMockRulesByScenarioPayload) => typedError<ApiResponse<MockRule[]>, string>(__TAURI_INVOKE("get_mock_rules_by_scenario", { payload })),
	createMockRule: (payload: CreateMockRulePayload) => typedError<ApiResponse<MockRule>, string>(__TAURI_INVOKE("create_mock_rule", { payload })),
	updateMockRule: (payload: UpdateMockRulePayload) => typedError<ApiResponse<MockRule>, string>(__TAURI_INVOKE("update_mock_rule", { payload })),
	deleteMockRule: (id: string) => typedError<boolean, string>(__TAURI_INVOKE("delete_mock_rule", { id })),
	createMockRuleFromLog: (payload: CreateMockFromLogPayload) => typedError<ApiResponse<MockRule>, string>(__TAURI_INVOKE("create_mock_rule_from_log", { payload })),
	getMockingStatus: () => typedError<ApiResponse<MockingSettings>, string>(__TAURI_INVOKE("get_mocking_status")),
	setScenarioEnabled: (id: string, enabled: boolean) => typedError<Scenario[], string>(__TAURI_INVOKE("set_scenario_enabled", { id, enabled })),
	getTailscaleIp: () => typedError<ApiResponse<string | null>, string>(__TAURI_INVOKE("get_tailscale_ip")),
	startCloudflareTunnel: () => typedError<ApiResponse<string>, string>(__TAURI_INVOKE("start_cloudflare_tunnel")),
	stopCloudflareTunnel: () => typedError<ApiResponse<null>, string>(__TAURI_INVOKE("stop_cloudflare_tunnel")),
	checkAdbStatus: () => typedError<ApiResponse<AdbStatus>, string>(__TAURI_INVOKE("check_adb_status")),
	startUsbReverse: (port: number) => typedError<ApiResponse<null>, string>(__TAURI_INVOKE("start_usb_reverse", { port })),
	stopUsbReverse: (port: number) => typedError<ApiResponse<null>, string>(__TAURI_INVOKE("stop_usb_reverse", { port })),
	processCrypto: (payload: ProcessCryptoPayload) => typedError<ApiResponse<string>, string>(__TAURI_INVOKE("process_crypto", { payload })),
	validateJsonSchema: (payload: ValidateSchemaPayload) => typedError<ApiResponse<SchemaValidationResult>, string>(__TAURI_INVOKE("validate_json_schema", { payload })),
	executePipeline: (payload: PipelineFlow) => typedError<ApiResponse<PipelineExecutionReport>, string>(__TAURI_INVOKE("execute_pipeline", { payload })),
	executePipelineApiNode: (configJson: string) => typedError<ApiResponse<string>, string>(__TAURI_INVOKE("execute_pipeline_api_node", { configJson })),
	getSavedPipelines: () => typedError<ApiResponse<SavedPipeline_Serialize[]>, string>(__TAURI_INVOKE("get_saved_pipelines")),
	getSavedPipeline: (payload: GetSavedPipelinePayload) => typedError<ApiResponse<SavedPipeline_Serialize | null>, string>(__TAURI_INVOKE("get_saved_pipeline", { payload })),
	createSavedPipeline: (payload: CreateSavedPipelinePayload_Deserialize) => typedError<ApiResponse<SavedPipeline_Serialize>, string>(__TAURI_INVOKE("create_saved_pipeline", { payload })),
	updateSavedPipeline: (payload: UpdateSavedPipelinePayload_Deserialize) => typedError<ApiResponse<SavedPipeline_Serialize | null>, string>(__TAURI_INVOKE("update_saved_pipeline", { payload })),
	deleteSavedPipeline: (payload: DeleteSavedPipelinePayload) => typedError<ApiResponse<boolean>, string>(__TAURI_INVOKE("delete_saved_pipeline", { payload })),
	importSavedPipelines: (payload: ImportSavedPipelinesPayload_Deserialize) => typedError<ApiResponse<SavedPipeline_Serialize[]>, string>(__TAURI_INVOKE("import_saved_pipelines", { payload })),
	getJsonSchemas: () => typedError<ApiResponse<SavedJsonSchema_Serialize[]>, string>(__TAURI_INVOKE("get_json_schemas")),
	getJsonSchema: (payload: GetJsonSchemaPayload) => typedError<ApiResponse<SavedJsonSchema_Serialize | null>, string>(__TAURI_INVOKE("get_json_schema", { payload })),
	createJsonSchema: (payload: CreateJsonSchemaPayload_Deserialize) => typedError<ApiResponse<SavedJsonSchema_Serialize>, string>(__TAURI_INVOKE("create_json_schema", { payload })),
	updateJsonSchema: (payload: UpdateJsonSchemaPayload_Deserialize) => typedError<ApiResponse<SavedJsonSchema_Serialize | null>, string>(__TAURI_INVOKE("update_json_schema", { payload })),
	deleteJsonSchema: (payload: DeleteJsonSchemaPayload) => typedError<ApiResponse<boolean>, string>(__TAURI_INVOKE("delete_json_schema", { payload })),
	importJsonSchemas: (payload: ImportJsonSchemasPayload_Deserialize) => typedError<ApiResponse<SavedJsonSchema_Serialize[]>, string>(__TAURI_INVOKE("import_json_schemas", { payload })),
	getCryptoPresets: () => typedError<ApiResponse<SavedCryptoPreset_Serialize[]>, string>(__TAURI_INVOKE("get_crypto_presets")),
	getCryptoPreset: (payload: GetCryptoPresetPayload) => typedError<ApiResponse<SavedCryptoPreset_Serialize | null>, string>(__TAURI_INVOKE("get_crypto_preset", { payload })),
	createCryptoPreset: (payload: CreateCryptoPresetPayload) => typedError<ApiResponse<SavedCryptoPreset_Serialize>, string>(__TAURI_INVOKE("create_crypto_preset", { payload })),
	updateCryptoPreset: (payload: UpdateCryptoPresetPayload) => typedError<ApiResponse<SavedCryptoPreset_Serialize | null>, string>(__TAURI_INVOKE("update_crypto_preset", { payload })),
	deleteCryptoPreset: (payload: DeleteCryptoPresetPayload) => typedError<ApiResponse<boolean>, string>(__TAURI_INVOKE("delete_crypto_preset", { payload })),
	importCryptoPresets: (payload: ImportCryptoPresetsPayload_Deserialize) => typedError<ApiResponse<SavedCryptoPreset_Serialize[]>, string>(__TAURI_INVOKE("import_crypto_presets", { payload })),
};

/* Types */
export type AdbStatus = {
	found: boolean,
	path: string | null,
	devices: string[],
};

export type AddLocalRoutePayload = {
	domainId: number,
	targetHost: string,
	targetPort: number,
};

export type Annotation = Annotation_Serialize | Annotation_Deserialize;

export type AnnotationLocator = AnnotationLocator_Serialize | AnnotationLocator_Deserialize;

export type AnnotationLocator_Deserialize = {
	strategy: LocatorStrategy,
	value?: string | null,
	role?: string | null,
	name?: string | null,
};

export type AnnotationLocator_Serialize = {
	strategy: LocatorStrategy,
	value?: string | null,
	role?: string | null,
	name?: string | null,
};

export type Annotation_Deserialize = {
	id?: string,
	selector?: string,
	content?: string,
	tagName?: string,
	thumbnail?: string,
	role?: string,
	description?: string,
	timestamp?: number | null,
	domain?: string,
	url?: string,
	hostPattern?: string | null,
	pathPattern?: string | null,
	/**  Priority-ordered locators. Index 0 is primary. */
	locators?: AnnotationLocator_Deserialize[],
	lastValidation?: LocatorValidation_Deserialize | null,
};

export type Annotation_Serialize = {
	id: string,
	selector: string,
	content: string,
	tagName: string,
	thumbnail: string,
	role: string,
	description: string,
	timestamp: number | null,
	domain: string,
	url: string,
	hostPattern: string | null,
	pathPattern: string | null,
	/**  Priority-ordered locators. Index 0 is primary. */
	locators: AnnotationLocator_Serialize[],
	lastValidation?: LocatorValidation_Serialize | null,
};

export type ApiLogEntry = {
	id: string,
	timestamp: string,
	method: string,
	url: string,
	host: string,
	path: string,
	status_code: number | null,
	request_headers: { [key in string]: string } | null,
	request_body: string | null,
	response_headers: { [key in string]: string } | null,
	response_body: string | null,
	/**  Present on list responses; true when a body sidecar exists (or legacy entry had bodies). */
	has_bodies?: boolean,
	is_mocked?: boolean,
};

export type ApiLogSearchHit = {
	summary: ApiLogSummary,
	snippet: string | null,
	/**  True when this hit came from a cold body scan (unlearned param). */
	from_scan?: boolean,
};

export type ApiLogSummary = {
	id: string,
	timestamp: string,
	method: string,
	url: string,
	host: string,
	path: string,
	status_code: number | null,
	has_bodies: boolean,
	is_mocked?: boolean,
};

export type ApiRequestResult = {
	statusCode: number,
	headers: { [key in string]: string },
	body: string,
	elapsedMs: number | null,
};

export type ApiResponse<T> = {
	message: string,
	success: boolean,
	data: T,
};

export type ClearApiLogsPayload = {
	date: string | null,
};

export type CreateCryptoPresetPayload = {
	name: string,
	description?: string,
	action: string,
	payload?: string,
	key?: string,
	iv?: string,
	code: string | null,
};

export type CreateGroupPayload = {
	name: string,
};

export type CreateJsonSchemaPayload = CreateJsonSchemaPayload_Serialize | CreateJsonSchemaPayload_Deserialize;

export type CreateJsonSchemaPayload_Deserialize = {
	name: string,
	description?: string,
	properties?: SchemaProperty_Deserialize[],
	schemaText?: string,
};

export type CreateJsonSchemaPayload_Serialize = {
	name: string,
	description: string,
	properties: SchemaProperty_Serialize[],
	schemaText: string,
};

export type CreateMockFromLogPayload = {
	logId: string,
	/**  Optional; when omitted, rules attach to the internal Default scenario. */
	scenarioId: string | null,
	name: string,
	logDate: string,
};

export type CreateMockRulePayload = {
	name: string,
	/**  Optional; when omitted, rules attach to the internal Default scenario. */
	scenarioId: string | null,
	host: string | null,
	method: string,
	urlPattern: string,
	responseStatus: number,
	responseHeaders: { [key in string]: string },
	responseBody: string | null,
	enabled: boolean,
};

export type CreateSavedPipelinePayload = CreateSavedPipelinePayload_Serialize | CreateSavedPipelinePayload_Deserialize;

export type CreateSavedPipelinePayload_Deserialize = {
	name: string,
	description?: string,
	flow: SavedPipelineFlow_Deserialize,
};

export type CreateSavedPipelinePayload_Serialize = {
	name: string,
	description: string,
	flow: SavedPipelineFlow_Serialize,
};

export type CreateScenarioPayload = {
	name: string,
	description: string | null,
};

export type CryptoAction = "base64Encode" | "base64Decode" | "urlEncode" | "urlDecode" | "hexEncode" | "hexDecode" | "jwtDecode" | "aesEncrypt" | "aesDecrypt" | "sha256" | "hmacSha256";

export type DeleteAnnotationPayload = {
	id: string,
};

export type DeleteCryptoPresetPayload = {
	id: string,
};

export type DeleteGroupPayload = {
	id: number,
};

export type DeleteJsonSchemaPayload = {
	id: string,
};

export type DeleteSavedPipelinePayload = {
	id: string,
};

export type Domain = {
	id: number,
	url: string,
};

/**
 *  도메인별 API 로깅 설정 링크.
 *  `domain_id`에 해당하는 도메인의 API 트래픽 로깅 여부와 바디 저장 여부를 제어.
 *  `schema_url`: OpenAPI/Swagger JSON을 다운로드할 수 있는 URL (선택).
 */
export type DomainApiLoggingLink = DomainApiLoggingLink_Serialize | DomainApiLoggingLink_Deserialize;

/**
 *  도메인별 API 로깅 설정 링크.
 *  `domain_id`에 해당하는 도메인의 API 트래픽 로깅 여부와 바디 저장 여부를 제어.
 *  `schema_url`: OpenAPI/Swagger JSON을 다운로드할 수 있는 URL (선택).
 */
export type DomainApiLoggingLink_Deserialize = {
	domainId: number,
	loggingEnabled?: boolean,
	bodyEnabled?: boolean,
	/**  OpenAPI/Swagger 스키마 다운로드 URL (예: <https://api.example.com/swagger.json>). */
	schemaUrl?: string | null,
};

/**
 *  도메인별 API 로깅 설정 링크.
 *  `domain_id`에 해당하는 도메인의 API 트래픽 로깅 여부와 바디 저장 여부를 제어.
 *  `schema_url`: OpenAPI/Swagger JSON을 다운로드할 수 있는 URL (선택).
 */
export type DomainApiLoggingLink_Serialize = {
	domainId: number,
	loggingEnabled: boolean,
	bodyEnabled: boolean,
	/**  OpenAPI/Swagger 스키마 다운로드 URL (예: <https://api.example.com/swagger.json>). */
	schemaUrl?: string | null,
};

export type DomainGroup = {
	id: number,
	name: string,
};

export type DomainGroupLink = {
	domain_id: number,
	group_id: number,
};

/**  Domain monitor settings (`check_enabled`, interval). Keyed by URL for import matching. */
export type DomainMonitorExport = {
	url: string,
	checkEnabled: boolean,
	intervalSecs: number,
};

/**  `DomainMonitorLink` + url (FE 표시용) */
export type DomainMonitorWithUrl = {
	domainId: number,
	url: string,
	checkEnabled: boolean,
	intervalSecs: number,
};

/**  체크 결과 구조. 최신은 `메모리(last_checks)`, 과거는 logs/{date}.json */
export type DomainStatusLog = {
	url: string,
	status: string,
	level: string,
	latency: number,
	ok: boolean,
	group: string,
	timestamp: string,
	errorMessage: string | null,
};

export type DownloadApiSchemaPayload = {
	domainId: number,
	/**  URL to fetch OpenAPI/Swagger schema from. */
	url: string,
};

export type GetAnnotationPayload = {
	id: string,
};

export type GetApiLogDetailPayload = {
	id: string,
	date: string | null,
};

export type GetApiLogsPayload = {
	date: string,
	domainFilter: string | null,
	methodFilter: string | null,
	hostFilter: string | null,
	exactMatch: boolean | null,
};

export type GetApiSchemaPayload = {
	domainId: number,
};

export type GetCryptoPresetPayload = {
	id: string,
};

export type GetDomainByIdPayload = {
	id: number,
};

export type GetDomainStatusLogsPayload = {
	date: string,
};

export type GetDomainsByGroupPayload = {
	groupId: number,
};

export type GetGroupsForDomainPayload = {
	domainId: number,
};

export type GetJsonSchemaPayload = {
	id: string,
};

export type GetMockRulesByScenarioPayload = {
	scenarioId: string,
};

export type GetSavedPipelinePayload = {
	id: string,
};

export type ImportAnnotationsPayload = ImportAnnotationsPayload_Serialize | ImportAnnotationsPayload_Deserialize;

export type ImportAnnotationsPayload_Deserialize = {
	annotations: Annotation_Deserialize[],
};

export type ImportAnnotationsPayload_Serialize = {
	annotations: Annotation_Serialize[],
};

export type ImportCryptoPresetsPayload = ImportCryptoPresetsPayload_Serialize | ImportCryptoPresetsPayload_Deserialize;

export type ImportCryptoPresetsPayload_Deserialize = {
	presets: SavedCryptoPreset_Deserialize[],
};

export type ImportCryptoPresetsPayload_Serialize = {
	presets: SavedCryptoPreset_Serialize[],
};

export type ImportDomainsPayload = {
	domains: Domain[],
};

export type ImportJsonSchemasPayload = ImportJsonSchemasPayload_Serialize | ImportJsonSchemasPayload_Deserialize;

export type ImportJsonSchemasPayload_Deserialize = {
	schemas: SavedJsonSchema_Deserialize[],
};

export type ImportJsonSchemasPayload_Serialize = {
	schemas: SavedJsonSchema_Serialize[],
};

export type ImportSavedPipelinesPayload = ImportSavedPipelinesPayload_Serialize | ImportSavedPipelinesPayload_Deserialize;

export type ImportSavedPipelinesPayload_Deserialize = {
	pipelines: SavedPipeline_Deserialize[],
};

export type ImportSavedPipelinesPayload_Serialize = {
	pipelines: SavedPipeline_Serialize[],
};

export type LocalRoute = {
	id: number,
	/**  Registered domain id (FK into domains.json). */
	domain_id?: number,
	/**  Hostname to match (e.g. api.example.com), cached from the linked domain URL. */
	domain: string,
	/**  Local target host (e.g. 127.0.0.1) */
	target_host: string,
	/**  Local target port */
	target_port: number,
	enabled: boolean,
};

export type LocatorStrategy = "testid" | "role" | "text" | "css" | "label";

export type LocatorValidation = LocatorValidation_Serialize | LocatorValidation_Deserialize;

export type LocatorValidationStatus = "ok" | "weak" | "broken" | "ambiguous";

export type LocatorValidation_Deserialize = {
	status: LocatorValidationStatus,
	checkedAt: number | null,
	primaryMatches: number,
	fallbackMatches?: number[],
	resolvedBy?: number | null,
	suggestPromoteTo?: number | null,
};

export type LocatorValidation_Serialize = {
	status: LocatorValidationStatus,
	checkedAt: number | null,
	primaryMatches: number,
	fallbackMatches: number[],
	resolvedBy?: number | null,
	suggestPromoteTo?: number | null,
};

export type MockRule = {
	id: string,
	name: string,
	scenario_id: string,
	host: string | null,
	method: string,
	url_pattern: string,
	response_status: number,
	response_headers: { [key in string]: string },
	response_body: string | null,
	enabled: boolean,
};

export type MockingSettings = {
	enabled: boolean,
};

export type NodeExecutionResult = {
	nodeId: string,
	success: boolean,
	elapsedMs: number | null,
	output: string,
	error: string | null,
};

export type PipelineEdge = {
	id: string,
	source: string,
	target: string,
};

export type PipelineExecutionReport = {
	success: boolean,
	elapsedMs: number | null,
	results: NodeExecutionResult[],
	error: string | null,
};

export type PipelineFlow = {
	nodes: PipelineNode[],
	edges: PipelineEdge[],
};

export type PipelineNode = {
	id: string,
	label: string,
	type: string,
	config: string,
};

export type PipelineNodePosition = {
	x: number | null,
	y: number | null,
};

export type ProcessCryptoPayload = {
	action: CryptoAction,
	payload: string,
	key: string | null,
	iv: string | null,
};

export type ProxySettings = {
	/**
	 *  Optional DNS server for pass-through resolution (e.g. "8.8.8.8" or "1.1.1.1:53").
	 *  When set, hosts not matching any local route are resolved via this server before forwarding.
	 */
	dns_server: string | null,
	/**  Port the local reverse proxy listens on (e.g. 8888). User-configurable to avoid conflicts. */
	proxy_port?: number,
	/**
	 *  Optional reverse HTTP port (e.g. 8080). When set, proxy listens here for direct HTTP.
	 *  No system proxy or hosts file: open <http://127.0.0.1:8080> and traffic is routed by Host (127.0.0.1 → first local route).
	 */
	reverse_http_port?: number | null,
	/**  Optional reverse HTTPS port (e.g. 8443). When set, proxy does TLS and forwards by Host. */
	reverse_https_port?: number | null,
	cors_rewrite_enabled?: boolean,
	tls_bypass_hosts?: string[],
	https_decrypt_hosts?: string[],
	connect_timeout_secs?: number,
	upstream_timeout_secs?: number,
	/**  Days to retain captured API logs on disk (e.g. 7, 14, 30, 90). 0 means keep forever. */
	log_retention_days?: number,
};

export type ProxyStatusPayload = {
	running: boolean,
	port: number,
	/**  Reverse HTTP listener port (no system proxy; use hosts + this port). */
	reverse_http_port: number | null,
	/**  Reverse HTTPS listener port (TLS by Host). */
	reverse_https_port: number | null,
};

export type RegistDomainsPayload = {
	urls: string[],
	groupId: number | null,
};

export type RemoveDomainApiLoggingPayload = {
	domainId?: number | null,
	domainIds?: number[] | null,
};

export type RemoveDomainsPayload = {
	id?: number | null,
	ids?: number[] | null,
};

export type RemoveLocalRoutePayload = {
	id: number,
};

export type SavedCryptoPreset = SavedCryptoPreset_Serialize | SavedCryptoPreset_Deserialize;

export type SavedCryptoPreset_Deserialize = {
	id: string,
	name: string,
	description: string,
	action: string,
	payload: string,
	key: string,
	iv: string,
	code?: string | null,
	createdAt: number | null,
	updatedAt: number | null,
};

export type SavedCryptoPreset_Serialize = {
	id: string,
	name: string,
	description: string,
	action: string,
	payload: string,
	key: string,
	iv: string,
	code?: string | null,
	createdAt: number | null,
	updatedAt: number | null,
};

export type SavedJsonSchema = SavedJsonSchema_Serialize | SavedJsonSchema_Deserialize;

export type SavedJsonSchema_Deserialize = {
	id: string,
	name: string,
	description: string,
	properties: SchemaProperty_Deserialize[],
	schemaText: string,
	createdAt: number | null,
	updatedAt: number | null,
};

export type SavedJsonSchema_Serialize = {
	id: string,
	name: string,
	description: string,
	properties: SchemaProperty_Serialize[],
	schemaText: string,
	createdAt: number | null,
	updatedAt: number | null,
};

export type SavedPipeline = SavedPipeline_Serialize | SavedPipeline_Deserialize;

export type SavedPipelineEdge = {
	id: string,
	source: string,
	target: string,
};

export type SavedPipelineFlow = SavedPipelineFlow_Serialize | SavedPipelineFlow_Deserialize;

export type SavedPipelineFlow_Deserialize = {
	nodes: SavedPipelineNode_Deserialize[],
	edges: SavedPipelineEdge[],
};

export type SavedPipelineFlow_Serialize = {
	nodes: SavedPipelineNode_Serialize[],
	edges: SavedPipelineEdge[],
};

export type SavedPipelineNode = SavedPipelineNode_Serialize | SavedPipelineNode_Deserialize;

export type SavedPipelineNode_Deserialize = {
	id: string,
	label: string,
	type: string,
	config: string,
	position?: PipelineNodePosition | null,
};

export type SavedPipelineNode_Serialize = {
	id: string,
	label: string,
	type: string,
	config: string,
	position?: PipelineNodePosition | null,
};

export type SavedPipeline_Deserialize = {
	id: string,
	name: string,
	description: string,
	flow: SavedPipelineFlow_Deserialize,
	createdAt: number | null,
	updatedAt: number | null,
};

export type SavedPipeline_Serialize = {
	id: string,
	name: string,
	description: string,
	flow: SavedPipelineFlow_Serialize,
	createdAt: number | null,
	updatedAt: number | null,
};

export type Scenario = {
	id: string,
	name: string,
	description: string | null,
	enabled: boolean,
};

/**  Schema 다운로드 응답: 저장된 파일 내용(텍스트) 반환. */
export type SchemaDownloadResult = {
	domainId: number,
	path: string,
	sizeBytes: number | null,
	/**  처음 N 글자 미리보기 (최대 500자). */
	preview: string,
};

export type SchemaProperty = SchemaProperty_Serialize | SchemaProperty_Deserialize;

export type SchemaProperty_Deserialize = {
	id: string,
	name: string,
	type: string,
	description: string,
	required: boolean,
	parentId?: string | null,
};

export type SchemaProperty_Serialize = {
	id: string,
	name: string,
	type: string,
	description: string,
	required: boolean,
	parentId?: string | null,
};

export type SchemaValidationResult = {
	valid: boolean,
	errors: string | null,
};

export type SearchApiLogsPayload = {
	date: string,
	query: string | null,
	hostFilter: string | null,
	methodFilter: string | null,
	statusFilter: number | null,
	/**  Structured JSON leaf key (adaptive index). When set and unlearned, triggers body scan. */
	paramKey: string | null,
	paramValue: string | null,
	limit: number | null,
};

export type SendApiRequestPayload = {
	method: string,
	url: string,
	headers?: { [key in string]: string },
	body: string | null,
};

export type SetDomainApiLoggingPayload = {
	domainId?: number | null,
	domainIds?: number[] | null,
	loggingEnabled: boolean,
	bodyEnabled: boolean,
	schemaUrl: string | null,
};

export type SetDomainGroupsPayload = {
	domainId?: number | null,
	domainIds?: number[] | null,
	groupIds: number[],
};

export type SetDomainMonitorCheckEnabledPayload = {
	domainIds: number[],
	enabled: boolean,
};

export type SetGroupDomainsPayload = {
	groupId: number,
	domainIds: number[],
};

export type SetInjectionDomainsPayload = {
	domains: string[],
};

export type SetLocalRouteEnabledPayload = {
	id: number,
	enabled: boolean,
};

export type SetHttpsDecryptHostPayload = {
	host?: string | null,
	hosts?: string[] | null,
	enabled: boolean,
};

export type UpdateProxySettingsPayload = {
	corsRewriteEnabled?: boolean | null,
	tlsBypassHosts?: string[] | null,
	httpsDecryptHosts?: string[] | null,
	connectTimeoutSecs?: number | null,
	upstreamTimeoutSecs?: number | null,
	logRetentionDays?: number | null,
};

export type SetProxyDnsServerPayload = {
	dnsServer: string | null,
};

export type SetProxyPortPayload = {
	port: number,
};

export type SetProxyReversePortsPayload = {
	reverseHttpPort: number | null,
	reverseHttpsPort: number | null,
};

export type SettingsExport = SettingsExport_Serialize | SettingsExport_Deserialize;

export type SettingsExport_Deserialize = {
	/**  Bundle schema version (`.hg.json`). Same as `version` for v3+. */
	schemaVersion?: number,
	version: number,
	app?: string,
	exportedAt: string,
	domains: Domain[],
	groups: DomainGroup[],
	domainGroupLinks: DomainGroupLink[],
	localRoutes: LocalRoute[],
	proxySettings: ProxySettings,
	scenarios?: Scenario[],
	mockRules?: MockRule[],
} & {
	/**  Monitor settings per domain (`check_enabled`, interval). Status logs are excluded. */
	domainMonitor?: DomainMonitorExport[],
} | {
	/**  Monitor settings per domain (`check_enabled`, interval). Status logs are excluded. */
	domain_status?: DomainMonitorExport[],
};

export type SettingsExport_Serialize = {
	/**  Bundle schema version (`.hg.json`). Same as `version` for v3+. */
	schemaVersion: number,
	version: number,
	app: string,
	exportedAt: string,
	domains: Domain[],
	groups: DomainGroup[],
	domainGroupLinks: DomainGroupLink[],
	localRoutes: LocalRoute[],
	proxySettings: ProxySettings,
	/**  Monitor settings per domain (`check_enabled`, interval). Status logs are excluded. */
	domainMonitor: DomainMonitorExport[],
	scenarios: Scenario[],
	mockRules: MockRule[],
};

export type SingleDomainPayload = {
	domain: string,
};

export type StartLocalProxyPayload = {
	port: number | null,
};

export type StartTransparentProxyPayload = {
	port: number | null,
	processNames?: string[] | null,
};

export type TransparentProxyStatus = {
	running: boolean,
	targetPort: number,
	activeConnections: number,
	errorMessage: string | null,
	experimental: boolean,
	processAllowlist: string[],
};

export type OsAppEntry = {
	name: string,
	pids: number[],
	instanceCount: number,
};

export type UpdateAnnotationPayload = UpdateAnnotationPayload_Serialize | UpdateAnnotationPayload_Deserialize;

export type UpdateAnnotationPayload_Deserialize = {
	id: string,
	role?: string | null,
	description?: string | null,
	domain?: string | null,
	url?: string | null,
	hostPattern?: string | null,
	pathPattern?: string | null,
	locators?: AnnotationLocator_Deserialize[] | null,
	lastValidation?: LocatorValidation_Deserialize | null,
	/**  When true, clears persisted lastValidation. */
	clearValidation?: boolean | null,
};

export type UpdateAnnotationPayload_Serialize = {
	id: string,
	role: string | null,
	description: string | null,
	domain: string | null,
	url: string | null,
	hostPattern: string | null,
	pathPattern: string | null,
	locators: AnnotationLocator_Serialize[] | null,
	lastValidation: LocatorValidation_Serialize | null,
	/**  When true, clears persisted lastValidation. */
	clearValidation: boolean | null,
};

export type UpdateCryptoPresetPayload = {
	id: string,
	name: string | null,
	description: string | null,
	action: string | null,
	payload: string | null,
	key: string | null,
	iv: string | null,
	/**  Nested Option: omit = no change; null = clear code; string = set */
	code?: string | null,
};

export type UpdateDomainByIdPayload = {
	id: number,
	url: string | null,
};

export type UpdateGroupPayload = {
	id: number,
	name: string,
};

export type UpdateJsonSchemaPayload = UpdateJsonSchemaPayload_Serialize | UpdateJsonSchemaPayload_Deserialize;

export type UpdateJsonSchemaPayload_Deserialize = {
	id: string,
	name: string | null,
	description: string | null,
	properties: SchemaProperty_Deserialize[] | null,
	schemaText: string | null,
};

export type UpdateJsonSchemaPayload_Serialize = {
	id: string,
	name: string | null,
	description: string | null,
	properties: SchemaProperty_Serialize[] | null,
	schemaText: string | null,
};

export type UpdateLocalRoutePayload = {
	id?: number | null,
	ids?: number[] | null,
	targetHost?: string | null,
	targetPort?: number | null,
	enabled?: boolean | null,
};

export type UpdateMockRulePayload = {
	id: string,
	name: string | null,
	host: string | null,
	method: string | null,
	urlPattern: string | null,
	responseStatus: number | null,
	responseHeaders: { [key in string]: string } | null,
	responseBody: string | null,
	enabled: boolean | null,
};

export type UpdateSavedPipelinePayload = UpdateSavedPipelinePayload_Serialize | UpdateSavedPipelinePayload_Deserialize;

export type UpdateSavedPipelinePayload_Deserialize = {
	id: string,
	name: string | null,
	description: string | null,
	flow: SavedPipelineFlow_Deserialize | null,
};

export type UpdateSavedPipelinePayload_Serialize = {
	id: string,
	name: string | null,
	description: string | null,
	flow: SavedPipelineFlow_Serialize | null,
};

export type ValidateSchemaPayload = {
	payload: string,
	schema: string,
};

/* Tauri Specta runtime */
async function typedError<T, E>(result: Promise<T>): Promise<{ status: "ok"; data: T } | { status: "error"; error: E }> {
    try {
        return { status: "ok", data: await result };
    } catch (e) {
        if (e instanceof Error) throw e;
        return { status: "error", error: e as any };
    }
}

